# Configuration example.
[general]
log_file = "/workspace/logs/iot-ble-server"
log_rotationTime = 168
log_level = 4
use_redis = true

# Http server settings.
[http_server]
bind = "0.0.0.0:10080"
tls_cert = ""
tls_key = ""
route_prefix = "/iot/ble"

# PostgreSQL settings.
#
# Please note that PostgreSQL 9.5+ is required.
[postgresql]
# PostgreSQL dsn (e.g.: postgres://user:password@hostname/database?sslmode=disable).
#
# Besides using an URL (e.g. 'postgres://user:password@hostname/database?sslmode=disable')
# it is also possible to use the following format:
# 'user=chirpstack_as dbname=chirpstack_as sslmode=disable'.
#
# The following connection parameters are supported:
#
# * dbname - The name of the database to connect to
# * user - The user to sign in as
# * password - The user's password
# * host - The host to connect to. Values that start with / are for unix domain sockets. (default is localhost)
# * port - The port to bind to. (default is 5432)
# * sslmode - Whether or not to use SSL (default is require, this is not the default for libpq)
# * fallback_application_name - An application_name to fall back to if one isn't provided.
# * connect_timeout - Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
# * sslcert - Cert file location. The file must contain PEM encoded data.
# * sslkey - Key file location. The file must contain PEM encoded data.
# * sslrootcert - The location of the root certificate file. The file must contain PEM encoded data.
#
# Valid values for sslmode are:
#
# * disable - No SSL
# * require - Always SSL (skip verification)
# * verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
# * verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
dsn = "postgres://iotware:iotware@33.33.33.116:5432/iotware?sslmode=disable"
automigrate = true
max_open_connections = 5
max_idel_connections = 2

# Redis settings
#
# Please note that Redis 2.6.0+ is required.
[redis]
# Redis url (e.g. redis://user:password@hostname/0)
#
# For more information about the Redis URL format, see:
# https://www.iana.org/assignments/uri-schemes/prov/redis
url = "redis://33.33.33.116:6379"

# MQTT settings.
[mqtt]
# MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
port = "1887"
host = "iotware"

# Connect with the given username (optional)
username = "internal-server"

# Connect with the given password (optional)
pasword = "internal@Passw0rd@"